### ISSUE TITLE
Image building from Dockerfile

### ISSUE THREAD

**Issue by laszlocph** [gimlet-io/gimlet#645]

**Comment by laszlocph** [comment]
Kaniko is promising.

We could launch Kubernetes jobs for each build.

```
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  initContainers:
  - name: download-source
    image: nixery.dev/shell/curl/unzip
    command: ["/bin/sh"]
    args: 
    - "-c"
    - |
      mkdir /source && \
      curl -L https://github.com/laszlocph/chatbot-ui/archive/refs/tags/latest.zip -o /source/source.zip && \
      unzip /source/source.zip -d /workspace
    volumeMounts:    
    - mountPath: /workspace
      name: workspace
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
      - "--dockerfile=chatbot-ui-latest/Dockerfile"
      - "--context=dir:///workspace/chatbot-ui-latest"
      - "--no-push"
    #   # - "--destination=gcr.io/uerhgiurehguirghreiughre/fewoifeuwjfew:latest"
    volumeMounts:    
    - mountPath: /workspace
      name: workspace
    #   - name: kaniko-secret
    #     mountPath: /secret
    # env:
    #   - name: GOOGLE_APPLICATION_CREDENTIALS
    #     value: /secret/kaniko-secret.json
  restartPolicy: Never
  volumes:
  - name: workspace
    emptyDir:
      sizeLimit: 500Mi
  #   - name: kaniko-secret
  #     secret:
  #       secretName: kaniko-secret
```
