### ISSUE TITLE
Helm template render

### ISSUE THREAD

**Issue by SorsOps** [gimlet-io/gimlet#859]
I'm getting an error during chart render when attempting to deploy

```
cannot run render template cannot template Helm chart chart requires kubeVersion: >=1.24.0-0 which is incompatible with Kubernetes v1.20.0
```

This is very strange considering my actual `kubectl version` is returning 

```
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.7
```

This is occuring when trying to use the following chart.

```
chart:
   repository: https://charts.truecharts.org
  name: penpot 
  version:  4.0.13
 ```
 https://artifacthub.io/packages/helm/truecharts/penpot
 
 Is this perhaps due to the helm versions you are using internally?
