### ISSUE TITLE
 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by SorsOps** [gimlet-io/gimlet#861]
I'm using a gimlet configuration file with the `manifests` key like so :

```
app: foo
env: default
namespace: apps
deploy:
  branch: master
  event: push
manifests: | 
  apiVersion: v1
  kind: Namespace
  metadata:
    name: example
  ---
  apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: foo
  namespace: bar
spec:
  interval: 60m
  url:  <REDACTED>

---

apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: bar
  namespace: bar
spec:
  interval: 60m
  releaseName: bar
  chart:
    spec:
      chart: bar
      version: 0.0.1
      sourceRef:
        kind: HelmRepository
        name: foo
      interval: 10m
  #etc
  ```
  
  This seems to deploy correctly through the use of the `gimlet-io/gimlet-artifact-shipper-action` action on github, however I cannot actually view the configuration in the Gimlet UI as this causes a panic. I understand it won't be formatted according to the standard one chart definition, but I would expect to see something about the configuration in the UI for developers
  
  ```
     panic: runtime error: invalid memory address or nil pointer dereference
 
 -> github.com/gimlet-io/gimlet/pkg/dx.ChartSchema
 ->   /home/runner/work/gimlet/gimlet/pkg/dx/helm.go:130

    github.com/gimlet-io/gimlet/pkg/dashboard/server.deploymentTemplates
      /home/runner/work/gimlet/gimlet/pkg/dashboard/server/api.go:524
    github.com/gimlet-io/gimlet/pkg/dashboard/server.deploymentTemplateForApp
      /home/runner/work/gimlet/gimlet/pkg/dashboard/server/api.go:499
    net/http.HandlerFunc.ServeHTTP
      /opt/hostedtoolcache/go/1.22.1/x64/src/net/http/server.go:2166
    github.com/gimlet-io/gimlet/pkg/dashboard/server/session.MustUser.func1.1
      /home/runner/work/gimlet/gimlet/pkg/dashboard/server/session/session.go:101
    net/http.HandlerFunc.ServeHTTP
      /opt/hostedtoolcache/go/1.22.1/x64/src/net/http/server.go:2166
    github.com/gimlet-io/gimlet/pkg/dashboard/server/session.SetCSRF.func1.1
      /home/runner/work/gimlet/gimlet/pkg/dashboard/server/session/session.go:83
    net/http.HandlerFunc.ServeHTTP
      /opt/hostedtoolcache/go/1.22.1/x64/src/net/http/server.go:2166
    github.com/gimlet-io/gimlet/pkg/dashboard/server/session.SetUser.func1.1
      /home/runner/work/gimlet/gimlet/pkg/dashboard/server/session/session.go:61
    net/http.HandlerFunc.ServeHTTP
      /opt/hostedtoolcache/go/1.22.1/x64/src/net/http/server.go:2166
    github.com/go-chi/chi/v5/middleware.Timeout.func1.1
      /home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/middleware/timeout.go:44

      ```
